### ISSUE TITLE
Not getting GLMapImage on custom location  

### ISSUE THREAD

**Issue by elluminati10** [GLMap/examples-ios#1]
Hello,

I set image on map like this way
UIImage *img =  [UIImage imageNamed:@"pin_icon"];
    _mapImage = [_mapView displayImage:img];
    if (_mapImage) {
         _mapImage.position = _mapView.mapCenter;
        _mapImage.offset = CGPointMake(img.size.width/2, 0);
        _mapImage.angle = arc4random_uniform(360);
        _mapImage.rotatesWithMap = YES;
    }

it's working fine.
but I not need to set image at _mapView.mapCenter, my requirement is I need to set image on custom position.
for that I wrote code like this way 
UIImage *img =  [UIImage imageNamed:@"pin_icon"];
    _mapImage = [_mapView displayImage:img];
    if (_mapImage) {
        // _mapImage.position = _mapView.mapCenter;
        _mapImage.position = GLMapPointMake(22.3039, 70.8022);
        _mapImage.offset = CGPointMake(img.size.width/2, 0);
        _mapImage.angle = arc4random_uniform(360);
        _mapImage.rotatesWithMap = YES;
    }

it is not woking, why ?

**Comment by destman** [comment]
Hi,
If you need to place object somewhere on map and you have it geo location (latitude, longitude) use function `GLMapPointMakeFromGeoCoordinates(lat, lon)` to calculate valid GLMapPoint (GLMapPoint is projected coordinates not geo coordinates...)

**Comment by elluminati10** [comment]
Thanks For Prompt reply, it's Working.
