### ISSUE TITLE
iOS Deprecating OpenGL?

### ISSUE THREAD

**Issue by stevenyix** [GLMap/examples-ios#10]
I have read that Apple is deprecating OpenGL and directing developers to use the Metal Renderer.  Do you have any idea how long apps submitted to the iOS App Store using GLMap will continue to be accepted?  

And do you plan on having a Metal-based SDK in the future.  Thanks.

**Comment by molind** [comment]
GLMap uses Metal renderer since version 1.0.3. Old iOS devices and Android devices still use OpenGL renderer.
