### ISSUE TITLE
Routing offline

### ISSUE THREAD

**Issue by jahir8a** [GLMap/examples-ios#12]
Regards,

Excellent work when creating GLMap is an excellent tool, but I have a problem, when I change the routing to offline I get the following error OperationQueue Worker2 / 2 signal SIGABRT could you help me solve it please and console I get the following message terminating with uncaught exception of type std::runtime_error: Unable to extract leap second information.

![image](https://user-images.githubusercontent.com/8550728/48282174-88cba780-e41e-11e8-8fd8-69267882fa1c.png)

**Comment by jahir8a** [comment]
thanks for the help I hope you can fix it soon

**Comment by molind** [comment]
Hello what is your timezone, iOS version, and locations departure and destination of that route? Valhalla uses iOS tzdata to work with timezones and in your case it can't find leap second information. I'll publish 1.0.5 update as soon as we fix it. Sorry for delay.

**Comment by molind** [comment]
I've checked on iOS12, and iOS9. Both initialized tzdata successfully. Without your information about this issue I can't reproduce and fix it.

**Comment by jahir8a** [comment]
> Hello what is your timezone, iOS version, and locations departure and destination of that route? Valhalla uses iOS tzdata to work with timezones and in your case it can't find leap second information. I'll publish 1.0.5 update as soon as we fix it. Sorry for delay.

I'm testing it in the xcode 9.2 simulator and the simulator has the following features
![captura de pantalla 2018-12-07 a la s 4 19 38 p m](https://user-images.githubusercontent.com/8550728/49675938-558c3080-fa3d-11e8-8b1d-2b2e4d0efd75.png)
![captura de pantalla 2018-12-07 a la s 4 20 28 p m](https://user-images.githubusercontent.com/8550728/49675941-57ee8a80-fa3d-11e8-8a56-bd5cb073fde3.png)
And it executed the following example with the default parameters and when switching to offline routes it appears the error that before mentioned
![captura de pantalla 2018-12-07 a la s 4 23 11 p m](https://user-images.githubusercontent.com/8550728/49676010-98e69f00-fa3d-11e8-8368-a6e48ee86e2e.png)
![captura de pantalla 2018-12-07 a la s 4 23 33 p m](https://user-images.githubusercontent.com/8550728/49676037-bb78b800-fa3d-11e8-8949-77c646686d3b.png)
I hope this feedback helps you understand my problem and help me solve it.
Thanks for all the help
regards

**Comment by jahir8a** [comment]
Thanks for the help I will review the folder and apply your request. I'll tell you if it worked, one more query on the physical device will not get this problem.

Thanks again for all the help and support.

**Comment by jahir8a** [comment]
> Gracias por la ayuda, revisaré la carpeta y aplicaré su solicitud. Le diré si funcionó, una consulta más en el dispositivo físico no tendrá este problema.
> 
> Gracias de nuevo por toda la ayuda y apoyo.

**Comment by jahir8a** [comment]
Check the path / var / db / timezone but the timezone folder does not exist so it will be tested on a real device or on another machine.
I appreciate all the help and support.

**Comment by molind** [comment]
I've found this discussion: https://forums.swift.org/t/timezone-database/6271/13

Seems you're using macOS Sierra and timezone data is contained at `/usr/share/zoneinfo`. Please create a symlink to `/var/db/timezone/zoneinfo` and it should work.

**Comment by jahir8a** [comment]
> I've found this discussion: https://forums.swift.org/t/timezone-database/6271/13
> 
> Seems you're using macOS Sierra and timezone data is contained at `/usr/share/zoneinfo`. Please create a symlink to `/var/db/timezone/zoneinfo` and it should work.

Thanks for the support, I will test your solution and comment if it solved my problem.

Congratulations for such an excellent tool.

**Comment by jahir8a** [comment]
Thanks your solution was successful resolved my problem, greetings and success
