### ISSUE TITLE
maps with contours

### ISSUE THREAD

**Issue by gnvo** [GLMap/examples-ios#13]
Hey,
Thanks for this awesome project!
I would like to display elevation contour overlays, but I haven't seen any example in this repo to do this, nor any reference to this on the guru maps app.
Are there plans, for GLMap to support maps with elevation contour lines?
In the time being, using a GeoJson would be an option?
Ps: I'm sorry if this is not the place to ask about this.
Thanks again!

**Comment by molind** [comment]
Hi!,
Right now you can display contour lines from GeoJSON. But first, you'll need to generate contour lines for the area you need. 
Check `gdal_contour` for that. 
We working now on compact and fast contour lines. They should be ready in the next major framework release.

**Comment by gnvo** [comment]
That's great news! when do you expect to have the next mayor framework release?

**Comment by gnvo** [comment]
I got it working with GeoJSON, but the file size is too big. Does GLMap have a way to read mbtiles or pbf? or do I need to bridge between those formats and GLMap?

**Comment by molind** [comment]
Can't say exactly. 1-3 months to go. Inventing compact binary format now. Trying to put contour lines with 10 meters step in less than 10 mb per 1 square degrees. (~300Mb in GeoJSON)
What about other formats. GeoJSON is common and easy way to load data. You can read geometry from any binary format and use `- [GLMapVectorObject  initWithPolygonOuterRings: innerRings:]` constructor for polygons. There is also `initWith*` constructors for points and lines.

**Comment by gnvo** [comment]
Ok, I will investigate.
In the meantime, I've been playing with navigation. It works well, but I haven't found a way to access the coordinates of the calculated route. I've checked:
GLMapTrack
GLMapTrackData
GLMapTrackLayer
GLRoute
GLMapTrackLayer
GLMapDrawObject
Is there a way to retrieve all the coordinates of the route?

**Comment by destman** [comment]
> Ok, I will investigate.
> In the meantime, I've been playing with navigation. It works well, but I haven't found a way to access the coordinates of the calculated route. I've checked:
> GLMapTrack
> GLMapTrackData
> GLMapTrackLayer
> GLRoute
> GLMapTrackLayer
> GLMapDrawObject
> Is there a way to retrieve all the coordinates of the route?
https://globus.software/docs/objc/api/latest/Classes/GLRoute.html#/c:objc(cs)GLRoute(im)enumManeuverPoints:withBlock:

**Comment by molind** [comment]
Route points stored in maneuvers. You can enumerate over maneuvers and request points from each maneuver using `enumManeuverPoints: withBlock:`. Then, optionally convert from `GLMapPoint` to `GLMapGeoPoint`.

**Comment by gnvo** [comment]
Super! thanks for the all the input. I got working the contours, but I'm looking forward to use your implementation!!
