### ISSUE TITLE
Adding two Vector Layers causes the second one not to display labels

### ISSUE THREAD

**Issue by jerzykiler** [GLMap/examples-ios#15]
I have created two geojson layers `layer_A` and `layer_B` and two mapcss styles `style_A` and `style_B`.
I added `layer_A` with `style_A` and `layer_B` with `style_B` to the mapView.

`layer_A` is a neighborhood and `layer_B` is one building inside this neighborhood meaning `layer_A` contains the area where objects from `layer_B` are in real life.

Layers contain nodes with properties like name:en, name:de etc, and styles support those properties:
```
node[name:en]{
    text:eval(tag("name:en"));
    text-color:#FFFFFF;
    font-size:16;
    font-stroke-width:1pt;
    font-stroke-color:#000000;
}
```

The problem is although both styles work with colors of areas/polygons the objects added later: `style_B` and `layer_B` does not show any labels. 

The Labels from `layer_B` are sometimes visible using very small zoom (far away view).

When I merge objects from `layer_A` and `layer_B` to one `layer_C` and merge styles to one `style_C` then everything is showing correctly.

Those same layers and styles work correctly on android without merging.

**Comment by molind** [comment]
Hello, Could you change a change demo app to show your issue? It would be much easier for us to fix it that way.

**Comment by jerzykiler** [comment]
I'll try to do it this week.

**Comment by jerzykiler** [comment]
Ok I started doing the demo app and magically it started working.

I was using the old version of GLMap before and I was creating GeoJSON objects like this:
```
        let data = NSData(contentsOfFile: fileName)!
        let str = String(data: data as Data, encoding: .utf8)!
        let objects = try! GLMapVectorObject.createVectorObjects(fromGeoJSON: str)
```

and I changed it to this like is in your newest demo:

```
        let path = Bundle.main.path(forResource: fileName, ofType: "geojson")!
        let objects = try! GLMapVectorObject.createVectorObjects(fromFile: path)
        return objects
```
and now it works

¯\\\_(ツ)_/¯

**Comment by molind** [comment]
Great. Should I close this issue for now?

**Comment by jerzykiler** [comment]
Yes, it can be closed.
