### ISSUE TITLE
Demo App Doesn't Download Maps

### ISSUE THREAD

**Issue by ussu99** [GLMap/examples-ios#2]
If I select 'Download offline Map'. The Show List is Empty. And I'm getting the following Error in the Debugconsole:
Map downloading error unauthorized.

Currently the Android Version can do downloads.

**Comment by molind** [comment]
You should enter your API key to download maps or tiles. It won't work otherwise.

**Comment by molind** [comment]
See
https://github.com/GLMap/examples-ios/blob/master/ObjCDemo/ObjCDemo/AppDelegate.m#L23
and
https://github.com/GLMap/examples-ios/blob/master/SwiftDemo/SwiftDemo/AppDelegate.swift#L21

**Comment by ussu99** [comment]
But Im using an  Api key.

**Comment by ussu99** [comment]
Is it possible that apikeys from a freshly created account arent functioning?

**Comment by ussu99** [comment]
Is the appname relevant for the creation of the apikey for this demo.

**Comment by molind** [comment]
Checking it.

**Comment by molind** [comment]
Most likely it's a typo in API key. Please check again and if it won't work send me your API key to check at support@getyourmap.com
