### ISSUE TITLE
Unable to load tiles

### ISSUE THREAD

**Issue by DSalehi** [GLMap/examples-ios#3]
Tiles aren't loading in SwiftExample (haven't checked Objective-C example). They load fine in my personal project using GLMap however, so I suspect it's something to do with SwiftExample code?

Also when I go to the "Download offline map" example, I get the following error
`HTTP Error 401 for http://cdn.getyourmap.com/map//maps2.json
2018-02-28 07:52:18.241961-0800 SwiftDemo[12873:6173138] Map downloading error unauthorized
`

**Comment by molind** [comment]
You should set apikey first.

**Comment by DSalehi** [comment]
Working now, issue was API key was being set using 
`GLMapManager.shared().apiKey = UserDefaults.standard.string(forKey: "my-api-key")`

but it worked when I switched it to 
`GLMapManager.shared().apiKey = "my-api-key"`
