### ISSUE TITLE
Map downloading error server error

### ISSUE THREAD

**Issue by CRivlaldo** [GLMap/examples-ios#5]
On the "Download offline map" screen I have no maps on the list and I see an error in the log:

> Map downloading error server error

Also, before this error I had another one:

> HTTP Error 401 for http://cdn.getyourmap.com/map//maps2.json

This URL doesn't look correct.

Versions of pods which I use are
GLMap (0.9.7)
GLMap+DefaultStyle (1.0.1)
GLMap+DynamicLib (0.9.7)
GLMap+WorldMap (18.01)
GLMapSwift (0.9.7)

**Comment by molind** [comment]
You should set API-key first.

**Comment by CRivlaldo** [comment]
I've set the API-key. As I remember there is another error in case of missed API-key.

**Comment by molind** [comment]
Please show me your code where you set an API key. HTTP error 401 means Unauthorized.

**Comment by CRivlaldo** [comment]
Yeah, it was my fault.

I had 

`GLMapManager.shared.apiKey = UserDefaults.standard.string(forKey: "my key")`

instead of 

`GLMapManager.shared.apiKey = "my key"`

Thanks!
