### ISSUE TITLE
Pricing clarification

### ISSUE THREAD

**Issue by jerzykiler** [GLMap/examples-ios#6]
According to your pricing policy:

![zrzut ekranu 2018-05-14 o 02 51 43](https://user-images.githubusercontent.com/2103762/39973597-eeac3d1a-5721-11e8-9219-1927bd1ac96b.png)

I want to be sure: if I use only offline geojson vectors that I made myself and don't ask any directions, map downloads or tile downloads can I use your "map views" (iOS offline framework) for free in a commercial app ?

**Comment by molind** [comment]
Correct. It's free for geojson only apps.
