### ISSUE TITLE
Example app crashes when tapping 'Offline' button in Routing

### ISSUE THREAD

**Issue by guidove** [GLMap/examples-ios#9]
Hi there,

Giving GetYourMap a try for 2nd version of my app (using other framework now). Really liking what I see so far. My app requires offline routing so wanted to give that a try in the demo app... and it crashes every time.

I'm on XCode10 GM. Tried on simulator and actual device (iPhone 6), both on iOS12. Both crash. I downloaded the belarus offline map before.

Here's what I see upon the crash:
<img width="2296" alt="screen shot 2018-09-19 at 23 17 09" src="https://user-images.githubusercontent.com/8523117/45795643-509bba00-bc62-11e8-947e-ad7fef26ced1.png">

Any thoughts?

Cheers,
Guido

**Comment by molind** [comment]
Make sure you have no changes inside valhalla.json file. Seems there is an error during config parsing. I've checked demo app few minutes ago and it worked without issues.

**Comment by guidove** [comment]
Sorry, it's not working for me. I didn't make any changes to valhalla.json, but replaced it with a newly downloaded version from the repository anyway, without any luck.

In the table cell it does say that downloading of navigation data is required for offline routing, but the demo app doesn't offer any way to do that as far as I can see. Could that be the issue? I assumed the navigation data was part of the offline map download, but if that's not the case...???

Also, I noticed, in the valhalla.json mjolnir section, it refers to valhalla-tiles in a folder with your nickname in it. That perhaps could explain why it's working for you and not for me? Not sure though.
```
"mjolnir": {
    "admin": "/Users/destman/git/molind/valhalla/valhalla_tiles/admins.sqlite",
    "hierarchy": true,
    "logging": {
      "color": false,
      "file_name": "path_to_some_file.log",
      "type": "std_out"
    },
    "max_cache_size": 1000000000,
    "shortcuts": true,
    "tile_dir": "/Users/destman/git/molind/valhalla/valhalla_tiles",
    "timezone": "/Users/destman/git/molind/valhalla/valhalla_tiles/timezones.sqlite",
    "transit_dir": "/data/valhalla/transit"
  }
```

**Comment by molind** [comment]
Yes, it's safe to remove this paths. Data loaded from navigation data extracts you download. Most interesting part for you is limits in config. By setting lower navigation limits you could make it use less memory.

BTW, it's just an exception happened not a crash, have you tried to continue app running? Or run it with disabled breakpoints.
